/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_DACMODE_DI 0x00u /*!<@brief Disables DAC mode */
#define IOCON_PIO_HYS_EN 0x20u     /*!<@brief Enable hysteresis */
#define IOCON_PIO_INV_DI 0x00u     /*!<@brief Input not invert */
#define IOCON_PIO_MODE_INACT 0x00u /*!<@brief No addition pin function */
#define IOCON_PIO_OD_DI 0x00u      /*!<@brief Disables Open-drain function */

/*!
 * @brief Hysteresis.: Disable */
#define PIO0_0_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_0_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_10_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_10_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_11_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_11_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_13_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_13_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_14_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_14_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_15_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_15_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_16_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_16_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_17_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_17_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_18_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_18_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_19_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_19_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_1_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_1_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_20_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_20_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_21_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_21_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_22_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_22_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_23_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_23_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_24_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_24_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_25_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_25_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_26_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_26_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_27_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_27_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_28_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_28_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_29_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_29_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_30_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_30_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_4_HYS_DISABLE 0x00u
/*!
 * @brief Invert input: Input not inverted (HIGH on pin reads as 1; LOW on pin reads as 0). */
#define PIO0_4_INV_NOT_INVERTED 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_4_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_7_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_7_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_8_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_8_MODE_INACTIVE 0x00u
/*!
 * @brief Hysteresis.: Disable */
#define PIO0_9_HYS_DISABLE 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_9_MODE_INACTIVE 0x00u

/*! @name PIO0_17 (number 1), NC0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NC0_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_NC0_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_NC0_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_NC0_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_NC0_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_NC0_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_13 (number 2), NC1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NC1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_NC1_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_NC1_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_NC1_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_NC1_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_NC1_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_27 (number 13), NC2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NC2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_NC2_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_NC2_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_NC2_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_NC2_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_NC2_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_26 (number 14), NC3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NC3_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_NC3_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_NC3_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_NC3_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_NC3_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_NC3_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_20 (number 15), NC4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NC4_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_NC4_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_NC4_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_NC4_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_NC4_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_NC4_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_30 (number 21), NC5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NC5_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_NC5_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_NC5_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_NC5_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_NC5_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_NC5_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_7 (number 22), NC6
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NC6_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_NC6_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_NC6_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_NC6_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_NC6_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_NC6_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PIO0_14 (number 25), STB
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STB_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STB_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_STB_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_STB_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_STB_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STB_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_19 (number 26), DIO
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DIO_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DIO_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_DIO_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_DIO_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_DIO_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DIO_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_25 (number 27), CLK
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_CLK_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_CLK_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_CLK_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_CLK_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_CLK_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_CLK_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_24 (number 28), LED_S4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_S4_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_S4_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_S4_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_S4_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_LED_S4_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_S4_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_23 (number 29), LED_S3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_S3_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_S3_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_S3_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_S3_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_LED_S3_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_S3_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_22 (number 30), LED_S2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_S2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_S2_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_S2_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_S2_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_LED_S2_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_S2_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_18 (number 31), LED_S1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_S1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_S1_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_S1_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_S1_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_LED_S1_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_S1_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_16 (number 32), NC7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_NC7_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_NC7_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_NC7_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_NC7_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_NC7_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_NC7_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_15 (number 16), Buzzer
  @{ */
#define BOARD_INITPINS_BUZZER_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_BUZZER_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_BUZZER_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
