/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: LPC804
package_id: LPC804M101JHI33
mcu_data: ksdk2_0
processor_version: 25.06.10
pin_labels:
- {pin_num: '5', pin_signal: PIO0_4/ADC_11, label: U0_TXD/SDA}
- {pin_num: '3', pin_signal: PIO0_12, label: nReload/ISP}
- {pin_num: '4', pin_signal: RESETN/PIO0_5, label: Reset}
- {pin_num: '8', pin_signal: PIO0_11/ADC_6/WKTCLKIN, label: nLink}
- {pin_num: '9', pin_signal: PIO0_10/ADC_7, label: CAPT_X3}
- {pin_num: '10', pin_signal: PIO0_21/ACMP_I5, label: CAPT_X2}
- {pin_num: '11', pin_signal: PIO0_29, label: CAPT_X1}
- {pin_num: '12', pin_signal: PIO0_28, label: CAPT_X0}
- {pin_num: '16', pin_signal: PIO0_15/ADC_8, label: Buzzer, identifier: BUZZER}
- {pin_num: '17', pin_signal: PIO0_1/ADC_0/ACMP_I2/CLKIN, label: ACMP_I2}
- {pin_num: '1', pin_signal: PIO0_17/ADC_9, label: NC0, identifier: NC0}
- {pin_num: '2', pin_signal: PIO0_13/ADC_10, label: NC1, identifier: NC1}
- {pin_num: '13', pin_signal: PIO0_27, label: NC2, identifier: NC2}
- {pin_num: '14', pin_signal: PIO0_26, label: NC3, identifier: NC3}
- {pin_num: '15', pin_signal: PIO0_20, label: NC4, identifier: NC4}
- {pin_num: '21', pin_signal: PIO0_30, label: NC5, identifier: NC5}
- {pin_num: '22', pin_signal: PIO0_7/ADC_1/ACMPVREF, label: NC6, identifier: NC6}
- {pin_num: '32', pin_signal: PIO0_16/ACMP_I4/ADC_3, label: NC7, identifier: NC7}
- {pin_num: '18', pin_signal: PIO0_9/ADC_4, label: CAPT_YH}
- {pin_num: '19', pin_signal: PIO0_8/ADC_5, label: CAPT_YL}
- {pin_num: '24', pin_signal: PIO0_0/ACMP_I1, label: U0_RXD/SLC}
- {pin_num: '25', pin_signal: PIO0_14/ACMP_I3/ADC_2, label: STB, identifier: STB}
- {pin_num: '26', pin_signal: PIO0_19/DACOUT, label: DIO, identifier: DIO}
- {pin_num: '27', pin_signal: PIO0_25, label: CLK, identifier: CLK}
- {pin_num: '28', pin_signal: PIO0_24, label: LED_S4, identifier: LED_S4}
- {pin_num: '29', pin_signal: PIO0_23, label: LED_S3, identifier: LED_S3}
- {pin_num: '30', pin_signal: PIO0_22, label: LED_S2, identifier: LED_S2}
- {pin_num: '31', pin_signal: PIO0_18, label: LED_S1, identifier: LED_S1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_iocon.h"
#include "fsl_gpio.h"
#include "fsl_swm.h"
#include "pin_mux.h"


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '1', peripheral: GPIO, signal: 'PIO0, 17', pin_signal: PIO0_17/ADC_9, direction: OUTPUT, gpio_init_state: 'false', mode: inactive, hysteresis: disabled}
  - {pin_num: '2', peripheral: GPIO, signal: 'PIO0, 13', pin_signal: PIO0_13/ADC_10, direction: OUTPUT, mode: inactive, hysteresis: disabled}
  - {pin_num: '5', peripheral: USART0, signal: TXD, pin_signal: PIO0_4/ADC_11, mode: inactive, invert: disabled, hysteresis: disabled}
  - {pin_num: '8', peripheral: GPIO, signal: 'PIO0, 11', pin_signal: PIO0_11/ADC_6/WKTCLKIN, mode: inactive, hysteresis: disabled}
  - {pin_num: '9', peripheral: CAPT, signal: 'CAPTX, 3', pin_signal: PIO0_10/ADC_7, mode: inactive, hysteresis: disabled}
  - {pin_num: '10', peripheral: CAPT, signal: 'CAPTX, 2', pin_signal: PIO0_21/ACMP_I5, mode: inactive, hysteresis: disabled}
  - {pin_num: '11', peripheral: CAPT, signal: 'CAPTX, 1', pin_signal: PIO0_29, mode: inactive, hysteresis: disabled}
  - {pin_num: '12', peripheral: CAPT, signal: 'CAPTX, 0', pin_signal: PIO0_28, mode: inactive, hysteresis: disabled}
  - {pin_num: '13', peripheral: GPIO, signal: 'PIO0, 27', pin_signal: PIO0_27, direction: OUTPUT, mode: inactive, hysteresis: disabled}
  - {pin_num: '14', peripheral: GPIO, signal: 'PIO0, 26', pin_signal: PIO0_26, direction: OUTPUT, mode: inactive, hysteresis: disabled}
  - {pin_num: '15', peripheral: GPIO, signal: 'PIO0, 20', pin_signal: PIO0_20, direction: OUTPUT, mode: inactive, hysteresis: disabled}
  - {pin_num: '17', peripheral: ACMP, signal: ACMP_IN2, pin_signal: PIO0_1/ADC_0/ACMP_I2/CLKIN, mode: inactive, hysteresis: disabled}
  - {pin_num: '18', peripheral: CAPT, signal: CAPTYH, pin_signal: PIO0_9/ADC_4, mode: inactive, hysteresis: disabled}
  - {pin_num: '19', peripheral: CAPT, signal: CAPTYL, pin_signal: PIO0_8/ADC_5, mode: inactive, hysteresis: disabled}
  - {pin_num: '21', peripheral: GPIO, signal: 'PIO0, 30', pin_signal: PIO0_30, direction: OUTPUT, mode: inactive, hysteresis: disabled}
  - {pin_num: '22', peripheral: GPIO, signal: 'PIO0, 7', pin_signal: PIO0_7/ADC_1/ACMPVREF, direction: OUTPUT, gpio_init_state: 'false', mode: inactive, hysteresis: disabled}
  - {pin_num: '24', peripheral: USART0, signal: RXD, pin_signal: PIO0_0/ACMP_I1, mode: inactive, hysteresis: disabled}
  - {pin_num: '25', peripheral: GPIO, signal: 'PIO0, 14', pin_signal: PIO0_14/ACMP_I3/ADC_2, direction: OUTPUT, gpio_init_state: 'true', mode: inactive, hysteresis: disabled}
  - {pin_num: '26', peripheral: GPIO, signal: 'PIO0, 19', pin_signal: PIO0_19/DACOUT, direction: OUTPUT, mode: inactive, hysteresis: disabled}
  - {pin_num: '27', peripheral: GPIO, signal: 'PIO0, 25', pin_signal: PIO0_25, direction: OUTPUT, mode: inactive, hysteresis: disabled}
  - {pin_num: '28', peripheral: GPIO, signal: 'PIO0, 24', pin_signal: PIO0_24, direction: OUTPUT, mode: inactive, hysteresis: disabled}
  - {pin_num: '29', peripheral: GPIO, signal: 'PIO0, 23', pin_signal: PIO0_23, direction: OUTPUT, mode: inactive, hysteresis: disabled}
  - {pin_num: '30', peripheral: GPIO, signal: 'PIO0, 22', pin_signal: PIO0_22, direction: OUTPUT, mode: inactive, hysteresis: disabled}
  - {pin_num: '31', peripheral: GPIO, signal: 'PIO0, 18', pin_signal: PIO0_18, direction: OUTPUT, mode: inactive, hysteresis: disabled}
  - {pin_num: '32', peripheral: GPIO, signal: 'PIO0, 16', pin_signal: PIO0_16/ACMP_I4/ADC_3, direction: OUTPUT, mode: inactive, hysteresis: disabled}
  - {pin_num: '16', peripheral: CTIMER0, signal: 'MATCH, 0', pin_signal: PIO0_15/ADC_8, mode: inactive, hysteresis: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitPins(void)
{
    /* Enables clock for IOCON.: enable */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    const uint32_t IOCON_INDEX_PIO0_config = (/* No addition pin function */
                                                     IOCON_PIO_MODE_INACT |
                                                     /* Enable hysteresis */
                                                     IOCON_PIO_HYS_EN |
                                                     /* Input not invert */
                                                     IOCON_PIO_INV_DI |
                                                     /* Disables Open-drain function */
                                                     IOCON_PIO_OD_DI);

	//IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_17, IOCON_INDEX_PIO0_config);
	//IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_13, IOCON_INDEX_PIO0_config);
	//IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_12, IOCON_INDEX_PIO0_config);
	//IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_5, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_4, IOCON_INDEX_PIO0_config);
	//IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_3, IOCON_INDEX_PIO0_config);
	//IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_2, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_11, IOCON_INDEX_PIO0_config);

	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_10, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_21, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_29, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_28, IOCON_INDEX_PIO0_config);
	//IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_27, IOCON_INDEX_PIO0_config);
	//IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_26, IOCON_INDEX_PIO0_config);
	//IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_20, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_15, IOCON_INDEX_PIO0_config);

	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_1, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_9, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_8, IOCON_INDEX_PIO0_config);
	//vdd
	//IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_30, IOCON_INDEX_PIO0_config);
	//IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_7, IOCON_INDEX_PIO0_config);
	//vrefp
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_0, IOCON_INDEX_PIO0_config);

	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_14, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_19, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_25, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_24, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_23, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_22, IOCON_INDEX_PIO0_config);
	IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_18, IOCON_INDEX_PIO0_config);
	//IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_16, IOCON_INDEX_PIO0_config);

    /* USART0_TXD connect to P0_4 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_TXD, kSWM_PortPin_P0_4);

    /* USART0_RXD connect to P0_0 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_RXD, kSWM_PortPin_P0_0);

    /* TimerMatchChannel0 connect to P0_15 */
    SWM_SetMovablePinSelect(SWM0, kSWM_T0_MAT_CHN0, kSWM_PortPin_P0_15);

    /* CAPT_X0 connect to P0_28 */
    SWM_SetMovablePinSelect(SWM0, kSWM_CAPT_X0, kSWM_PortPin_P0_28);

    /* CAPT_X1 connect to P0_29 */
    SWM_SetMovablePinSelect(SWM0, kSWM_CAPT_X1, kSWM_PortPin_P0_29);

    /* CAPT_X2 connect to P0_21 */
    SWM_SetMovablePinSelect(SWM0, kSWM_CAPT_X2, kSWM_PortPin_P0_21);

    /* CAPT_X3 connect to P0_10 */
    SWM_SetMovablePinSelect(SWM0, kSWM_CAPT_X3, kSWM_PortPin_P0_10);

    /* CAPT_YL connect to P0_8 */
    SWM_SetMovablePinSelect(SWM0, kSWM_CAPT_YL, kSWM_PortPin_P0_8);

    /* CAPT_YH connect to P0_9 */
    SWM_SetMovablePinSelect(SWM0, kSWM_CAPT_YH, kSWM_PortPin_P0_9);

    /* ACMP_INPUT2 connect to P0_1 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ACMP_INPUT2, true);

    gpio_pin_config_t STB_config = {
            .pinDirection = kGPIO_DigitalOutput,
            .outputLogic = 1U,
        };
        /* Initialize GPIO functionality on pin PIO0_14 (pin 25)  */
        GPIO_PinInit(BOARD_INITPINS_STB_GPIO, BOARD_INITPINS_STB_PORT, BOARD_INITPINS_STB_PIN, &STB_config);

        gpio_pin_config_t LED_S1_config = {
            .pinDirection = kGPIO_DigitalOutput,
            .outputLogic = 0U,
        };
        /* Initialize GPIO functionality on pin PIO0_18 (pin 31)  */
        GPIO_PinInit(BOARD_INITPINS_LED_S1_GPIO, BOARD_INITPINS_LED_S1_PORT, BOARD_INITPINS_LED_S1_PIN, &LED_S1_config);

        gpio_pin_config_t DIO_config = {
            .pinDirection = kGPIO_DigitalOutput,
            .outputLogic = 1U,
        };
        /* Initialize GPIO functionality on pin PIO0_19 (pin 26)  */
        GPIO_PinInit(BOARD_INITPINS_DIO_GPIO, BOARD_INITPINS_DIO_PORT, BOARD_INITPINS_DIO_PIN, &DIO_config);

        gpio_pin_config_t LED_S2_config = {
            .pinDirection = kGPIO_DigitalOutput,
            .outputLogic = 0U,
        };
        /* Initialize GPIO functionality on pin PIO0_22 (pin 30)  */
        GPIO_PinInit(BOARD_INITPINS_LED_S2_GPIO, BOARD_INITPINS_LED_S2_PORT, BOARD_INITPINS_LED_S2_PIN, &LED_S2_config);

        gpio_pin_config_t LED_S3_config = {
            .pinDirection = kGPIO_DigitalOutput,
            .outputLogic = 0U,
        };
        /* Initialize GPIO functionality on pin PIO0_23 (pin 29)  */
        GPIO_PinInit(BOARD_INITPINS_LED_S3_GPIO, BOARD_INITPINS_LED_S3_PORT, BOARD_INITPINS_LED_S3_PIN, &LED_S3_config);

        gpio_pin_config_t LED_S4_config = {
            .pinDirection = kGPIO_DigitalOutput,
            .outputLogic = 0U,
        };
        /* Initialize GPIO functionality on pin PIO0_24 (pin 28)  */
        GPIO_PinInit(BOARD_INITPINS_LED_S4_GPIO, BOARD_INITPINS_LED_S4_PORT, BOARD_INITPINS_LED_S4_PIN, &LED_S4_config);

        gpio_pin_config_t CLK_config = {
            .pinDirection = kGPIO_DigitalOutput,
            .outputLogic = 1U,
        };
        /* Initialize GPIO functionality on pin PIO0_25 (pin 27)  */
        GPIO_PinInit(BOARD_INITPINS_CLK_GPIO, BOARD_INITPINS_CLK_PORT, BOARD_INITPINS_CLK_PIN, &CLK_config);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
